#!/usr/bin/env python

import sys

try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen


def run(url):
    print(urlopen(url).read().decode('utf-8'))
    return 0


if __name__ == '__main__':
    url = sys.argv[-1]
    sys.exit(run(url))
